# NCBI E-utilities configuration
# Docs: https://www.ncbi.nlm.nih.gov/books/NBK25497/
email   = "michael.meuli@gmail.com"   # required by NCBI
# optional: raises rate limit to 10 req/s:
# [System.Environment]::SetEnvironmentVariable("NCBI_API_KEY", "your_key", "User")


# --- erm(41) ---

[[genome]]
accession = "NC_010397.1"       # Mycobacteroides abscessus ATCC 19977 complete genome
locus_tag = "MAB_2297"          # erm(41) CDS
output    = "erm41/erm41_abscessus_ATCC_19977.fasta"

[[genome]]
# Mycobacteroides abscessus subsp. bolletii CIP 108541 — WGS contig
# Coordinates taken from NCBI FASTA header: NZ_JRMF01000040.1:92072-92593
accession = "NZ_JRMF01000040.1"
locus_tag = "QP40_RS10855"          # erm(41) CDS
output    = "erm41/erm41_bolletii_CIP_108541.fasta"

# Mycobacteroides abscessus subsp. massiliense CCUG 48898 — WGS contig
# assembly: NZ_MVHY01000001.1
# erm41_massiliense_CCUG_48898.fasta was done manually. (deletion neart the end, but the end is still there)



# Direct accession (no locus_tag / coordinates) — fetches the accession as-is:
# [[genome]]
# accession = "AB123456.1"   # M. example strain — hsp65
# output    = "hsp65/hsp65_example.fasta"






# Direct accession example:
# [[append]]
# accession = "AB123456.1"   # M. example strain — hsp65
# fasta     = "myco_hsp65.fasta"

# Genome / locus_tag example:
# [[append]]
# accession = "NZ_JRMF01000040.1"   # M. abscessus subsp. bolletii CIP 108541
# locus_tag = "QP40_RS10855"        # erm(41) CDS
# fasta     = "myco_erm41.fasta"

# Genome / explicit coordinates example:
# [[append]]
# accession = "NZ_JRMF01000040.1"
# seq_start = 92072
# seq_stop  = 92593
# fasta     = "myco_erm41.fasta"

