use super::{REF_MYCO_RRS, SeqIdHit, best_alignment, parse_multi_fasta, reverse_complement};

/// Align `query` against every sequence in `database` and return all hits sorted by identity descending.
///
/// ### Generation of species identification databases
///
/// The database sequences are flagged as type material using the
/// [INSD Collaboration `type_material` qualifier](https://pmc.ncbi.nlm.nih.gov/articles/PMC4383940/).
/// Type material ties formal species names to physical specimens (culture collections for prokaryotes,
/// museum or herbarium specimens for eukaryotes), as annotated in the
/// [NCBI Taxonomy Database](http://www.ncbi.nlm.nih.gov/taxonomy).
///
/// species_hits only used in preview_16s()
/// but database also used for seq_id_hits by identify_sequence_hsp65() and identify_sequence_rrl_ntm() but not by identify_sequence_erm41().
pub fn identify_species(query: &[u8], database: &str) -> Vec<SeqIdHit> {
    let rc = reverse_complement(query);
    let mut hits: Vec<SeqIdHit> = parse_multi_fasta(database)
        .into_iter()
        .map(|(accession, description, refseq)| {
            let (fwd_id, fwd_off) = best_alignment(query, &refseq);
            let (rev_id, rev_off) = best_alignment(&rc, &refseq);
            let (identity, is_reverse, aligned_query, alignment_offset) = if rev_id > fwd_id {
                (rev_id, true, rc.clone(), rev_off)
            } else {
                (fwd_id, false, query.to_vec(), fwd_off)
            };
            SeqIdHit {
                accession,
                description,
                identity,
                is_reverse,
                aligned_query,
                alignment_offset,
                ref_seq: refseq,
                kansasii_gastri_snp_calls: vec![],
                marinum_ulcerans_snp_calls: vec![],
                rrl_snp_calls: vec![],
                erm41_snp_calls: vec![],
                erm41_position_28_opt: None,
                rrl_position_2057_2058_opt: None,
            }
        })
        .collect();
    hits.sort_by(|a, b| {
        b.identity
            .partial_cmp(&a.identity)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    hits
}

/// Database was generated by filtering NCBI Nucleotide for Mycobacteriaceae[Organism] AND (16S[Title] OR rrs[Gene Name]) AND 400:3000[SLEN] AND type_material[Filter] (via fetch_myco_sequences() in build.rs).
/// Added to this database are the rrs sequences found in [ntm-db](https://github.com/pathogen-profiler/ntm-db) (via extract_ntm_db_sequences() in build.rs).
pub fn identify_species_16s(query: &[u8]) -> Vec<SeqIdHit> {
    identify_species(query, REF_MYCO_RRS)
}
